spring.application.name=uberApp

#Database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/uberapp?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=
spring.datasource.password=

#JPA specification
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true